AWSTemplateFormatVersion: '2010-09-09'
Description: 'ES2 machine for pbpMyAdmin'
Parameters:
  KeyName:
    Description: 'Key Pair name'
    Type: 'AWS::EC2::KeyPair::KeyName'
    Default: webserver
  VPC:
    Description: 'Just select the one and only default VPC'
    Type: 'AWS::EC2::VPC::Id'
    Default: 'vpc-feb2a199'
    AllowedValues: ['vpc-feb2a199']
  Subnet:
    Description: 'Just select one of the available subnets'
    Type: 'AWS::EC2::Subnet::Id'
    AllowedValues: ['subnet-0a889651']
  InstanceType:
    Description: Select one of the possible instance types'
    Type: String
    Default: 't2.micro'
    AllowedValues: ['t2.micro', 't2.small', 't2.medium']